controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - Rev1
      - Rev2
      - Rev3
      - Rev4
      - Rev5
      - Rev6
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_servo
initial:  # Define initial robot poses per group
  - group: arm
    pose: home