arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Rev1
    - Rev2
    - Rev3
    - Rev4
    - Rev5
    - Rev6
  gains:
    Rev1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_servo
  gains:
    gripper_servo:
      p: 100
      d: 1
      i: 1
      i_clamp: 1